version: '3.8'

services:
  # squid:
  #   build: .
  #   container_name: squid-proxy
  #   ports:
  #     - "3128:3128"
  #   command: [ "squid", "-N", "-d", "1" ]
  #   volumes:
  #     - ./squid-config/squid.conf:/etc/squid/squid.conf
  #     - squid-cache:/var/spool/squid
  #     # - squid-logs:/var/log/squid
  #     - ./logs:/var/log/squid        # <-- เพิ่มให้ log อยู่ใน ./logs
  #   restart: unless-stopped
  #   networks:
  #     - proxy-net

  # fail2ban:
  #   image: crazymax/fail2ban:latest
  #   container_name: fail2ban
  #   privileged: true  # จำเป็นสำหรับ iptables access
  #   # network_mode: "host"
  #   networks:
  #     - proxy-net
  #   volumes:
  #     # โฟลเดอร์ config ทั้งหมด
  #     - ./fail2ban-config:/data
  #     # ตรงนี้ read-only ให้ Fail2ban แค่ดู log
  #     # แต่ถ้าอยากดู log อื่นด้วยก็อาจ mount เพิ่ม
  #     - ./logs:/var/log/squid:ro
  #     - ./logs/webmin:/var/webmin:ro
  #     # ไม่ต้อง mount /etc/fail2ban ซ้ำ ถ้าโฮสต์ไม่มีไฟล์ fail2ban ติดตั้ง
  #     # - /etc/fail2ban:/etc/fail2ban
  #   restart: always

    
  webmin:
    build: ./webmin-docker
    container_name: webmin
    # network_mode: "host"
    ports:
      - "10000:10000"
      - "3128:3128"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs/webmin:/var/webmin
      - ./logs:/var/log/squid
      - squid-cache:/var/spool/squid
      - ./fail2ban-config/jail.local:/etc/fail2ban/jail.local:ro
      - ./squid-config/squid.conf:/etc/squid/squid.conf:rw
    restart: unless-stopped
    networks:
      - proxy-net


volumes:
  squid-cache:

networks:
   proxy-net:
     driver: bridge
